//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public Bug()
        {
            this.State = new HashSet<State>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string description { get; set; }
        public string tester_id { get; set; }
        public string programmer_id { get; set; }
        public string date { get; set; }
    
        public virtual ICollection<State> State { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
