//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testapp
{
    using System;
    using System.Collections.Generic;
    
    public static class User
    {
       
    
        public static int Id { get; set; }
        public static string last_name { get; set; }
        public static string password { get; set; }
        public static string name { get; set; }
        public static string position { get; set; }
    
       
    }
}
